import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import Header from "../../components/Header";
import Sidebar from "../../components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className=" w-full">
      {/* <Header />
      <div className="w-full flex">
        <Sidebar />
        {children}
      </div> */}
    </div>
  );
}
